import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import { pinoHttp } from "pino-http";
import { env } from "./config/env.js";
import { logger } from "./lib/logger.js";
import { requestContext } from "./middleware/request-context.js";
import { errorHandler } from "./middleware/error-handler.js";
import { agentsRouter } from "./routes/agents.js";
import { dashboardRouter } from "./routes/dashboard.js";
import { toolsRouter } from "./routes/tools.js";
import { webhooksRouter } from "./routes/webhooks.js";

export const app = express();
app.disable("x-powered-by");
app.use(requestContext);
app.use(pinoHttp({ logger }));
app.use(helmet());
app.use(cors({ origin: env.FRONTEND_URL, credentials: true }));
app.use("/webhooks", webhooksRouter);
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.get("/health", (_req, res) => res.json({ status: "ok", service: "voxadesk-ai-backend" }));
app.use("/api/v1/dashboard", dashboardRouter);
app.use("/api/v1/agents", agentsRouter);
app.use("/api/v1/tools", toolsRouter);
app.use((_req, res) => res.status(404).json({ code: "NOT_FOUND", message: "Route not found." }));
app.use(errorHandler);
